---
title: "Load Historical Data"
author: "Hope Johnson"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
##Define package list
Packages<-c("tidyverse", "skimr", "lubridate", "zoo", "plotly", "glue")
.packages = Packages
##Install CRAN packages (if not already installed)
.inst <- .packages %in% installed.packages()
if(length(.packages[!.inst]) > 0) install.packages(.packages[!.inst])
##Load packages into session 
lapply(.packages, require, character.only=TRUE)
devtools::install_github("uclalawcovid19behindbars/behindbarstools")
library(behindbarstools)

get_first_not_na <- function(x){
    if(all(is.na(x))){
        return(NA)
    }
    return(na.omit(x)[1])
}
this_dir <- file.path("~", "UCLA", "code", "year-in-review")
data_path <- file.path(this_dir, "data", "processed")
```

# Load data

Load up all the states for which I have cleaned historical data ! Be sure to `git pull` from historical data repo first to get the most up-to-date data. 

```{r}
# historical_data_path <- file.path("~", "UCLA", "code", "historical-data", "data")
# hist_dat_files <-
#     list.files(path = historical_data_path, 
#                pattern = "*.csv",
#                full.names = TRUE) 
# 
# ## set column types 
# jnk <- read.csv(hist_dat_files[1], nrows=1, check.names=FALSE)
# # all columns are character columns unless otherwise denoted
# ctypes <- rep("c", ncol(jnk))
# names(ctypes) <- names(jnk)
# ctypes[stringr::str_starts(names(ctypes), "Residents|Staff")] <- "d"
# ctypes[names(ctypes) == "Date"] <- "D"

all_dat <- read_scrape_data(all_dates = TRUE)

dat_df <- all_dat %>% 
  filter(Date > "2020-04-29" & Date < "2021-05-01",
         !str_detect(Name, "(?i)statewide"),
         !str_detect(Name, "(?i)state-wide")) %>%
  mutate(NameToShow = glue('{stringr::str_to_title(Name)}, {State}'))

# dat_df <- hist_dat_files %>% 
#   map_df(~readr::read_csv(., col_types = paste0(ctypes, collapse = ""))) %>%
#   mutate(NameToShow = glue('{stringr::str_to_title(Name)}, {State}')) %>%
#   filter(!str_detect(Name, "(?i)statewide"),
#          !str_detect(Name, "(?i)state-wide")) 
```

## Translate data to a new format for plots

Create data set with Residents.Confirmed first. 

```{r}
# TO DO : add conditional highlight column

facs_to_highlight <- c(100, 
                       652, 
                       83,
                       115,
                       113)

long_dat <- dat_df %>%
  select(Facility.ID, State, Name, NameToShow, Date, Residents.Confirmed, Jurisdiction) %>%
  arrange(Date) %>%
  group_by(State, Name, Jurisdiction) %>% # don't have facility.ID for 100%
  mutate(lag_value = dplyr::lag(Residents.Confirmed, order_by = Date),
         diff = Residents.Confirmed - lag_value,
         Residents.Confirmed_cln = ifelse(diff < -5, NA, Residents.Confirmed), # drops in cumulative cases >5 become NA
         outbreak = ifelse(diff > 4, TRUE, FALSE),
         outbreak = ifelse(is.na(outbreak), FALSE, outbreak),
         ## try with a longer number of positions to lag by
         lag_three = dplyr::lag(Residents.Confirmed, n = 3, order_by = Date),
         diff_three = Residents.Confirmed - lag_three,
         outbreak_alt = ifelse(diff_three > 4, TRUE, FALSE),
         outbreak_alt = ifelse(is.na(outbreak_alt), FALSE, outbreak_alt),
         ) %>% 
  fill(Residents.Confirmed_cln) %>% # fill in missing values with last value (above)
  ungroup() %>%
  mutate(highlightFac = ifelse(Facility.ID %in% facs_to_highlight,
                               TRUE,
                               FALSE))

filled_dates <- long_dat %>% 
  group_by(State, Name, Jurisdiction) %>% # don't have facility.ID for 100%
  complete(Date = full_seq(Date, 1)) %>%
  fill(Residents.Confirmed_cln, #fill in missing values with last value (above)
       NameToShow,
       Facility.ID,
       highlightFac,
       outbreak,
       outbreak_alt) %>% 
  arrange(Date) %>%
  ## recalculate lags
  mutate(lag_value = dplyr::lag(Residents.Confirmed_cln, order_by = Date),
         diff = Residents.Confirmed_cln - lag_value,
         # perc_change = diff / lag_value,
         # perc_change = ifelse(is.infinite(perc_change), 1, perc_change),
         # large_perc_change = ifelse(perc_change > .4, TRUE, FALSE)
         ) %>%
  relocate(Facility.ID, State, Name, NameToShow, Date, Residents.Confirmed, Residents.Confirmed_cln) %>%
  ungroup() %>% 
  ## NYC jails big spike looks crazy
  filter(Name != "NEW YORK CITY JAILS",
         NameToShow != "Smith County Jail, Texas")

## filter out facilities with <19 case change over the entire year
filt_filled_dates <- filled_dates %>%
  group_by(Facility.ID) %>%
  arrange(Date) %>%
  mutate(total_change = last(Residents.Confirmed) - first(Residents.Confirmed)) %>%
  ungroup() %>%
  filter(total_change > 19)

# filled_dates %>% filter(Name == "LOS ANGELES JAILS") %>% View() # 360 obs
# long_dat %>% filter(Name == "LOS ANGELES JAILS") %>% View()

## test outbreaks highlight just on LA jails
la_jails <- filled_dates %>%
  filter(Name == "LOS ANGELES JAILS") %>%
  ggplot(.) +
  ggplot2::geom_point(aes(
    x = Date,
    y = Residents.Confirmed_cln, # change 7-day average, 15-day average, etc here
    group = Facility.ID,
    color = outbreak_alt,
    size = 2),
    ) +
  scale_x_date(date_breaks = "1 months", date_labels = "%b '%y") +
  scale_y_continuous(labels = scales::comma) 
ggplotly(la_jails)

large_facs_to_label <- filt_filled_dates %>% 
  filter(Residents.Confirmed_cln > 2215) %>% 
  group_by(Facility.ID) %>% 
  slice(which.max(Date)) %>%
  ungroup() %>%
  mutate(labeller = glue('{str_to_title(Name)}\n{State}'))

## check long dat looks ok
outbreaks_graph <- 
  filt_filled_dates %>%
  ggplot(.) +
  ggplot2::geom_line(aes(
    x = Date,
    y = Residents.Confirmed_cln, # change 7-day average, 15-day average, etc here
    group = Facility.ID,
    color = outbreak_alt,
    )) +
  scale_x_date(date_breaks = "1 months", date_labels = "%b '%y") +
  scale_y_continuous(
    limits = c(0, 4000),
    expand = c(0, 0),
    sec.axis = dup_axis(
      breaks = large_facs_to_label$Residents.Confirmed_cln,
      labels = large_facs_to_label$labeller,
      name = NULL
    ),
    labels = scales::comma
  ) + 
  labs(x = "",
       y = "Cumulative COVID-19 Cases Among Incarcerated People",
       title = "COVID-19 Cases In Prisons and Jails") +
  theme_behindbars() + 
  scale_color_manual(values=c("#dddddd", "#D7790F")) + 
  theme(legend.position = "none",
        axis.text.y = element_text(size = 15))
ggsave(file.path(this_dir, "plots", "highlight_outbreaks.png"), outbreaks_graph, width = 18, height = 10)

res_cases_dat <- 
  filt_filled_dates %>%
  select(State, Name, NameToShow, Date, Residents.Confirmed_cln, 
         Jurisdiction, highlightFac) %>%
  arrange(Date) %>%
  pivot_wider(names_from = Date, values_from = Residents.Confirmed_cln) %>%
  mutate(countReal = rowSums(!is.na(select(., -State, -Name, -Jurisdiction, 
                                           -NameToShow, -highlightFac)))) %>%
  # filter(countReal > 90) %>% # only keep data we have values for more than 3 months
  select(NameToShow, highlightFac, `2020-04-30`:`2021-04-30`) 

res_cases_dat %>% 
  filter(NameToShow == "Los Angeles Jails, California") %>% 
  View()

## any list columns with length > 1? check 
res_cases_dat %>% 
  filter(if_any(where(is.list), ~ lengths(.x) > 1))

# write_csv(res_cases_dat, file.path(data_path, "cumulative_cases.csv"))
write_csv(res_cases_dat, file.path(data_path, "cumulative_cases_wide.csv"))
```

Next, create a data set with estimated active cases.

```{r}
active_case_dat <- dat_df %>%
  select(State, Name, NameToShow, Date, Jurisdiction, 
         Residents.Confirmed, Residents.Active) %>%
  group_by(Name, State, Jurisdiction) %>%
  arrange(Date) %>%
  mutate(EstimatedActive = diff_roll_sum(Residents.Confirmed, Date)) %>%
  ungroup()

active_cases <- active_case_dat %>% 
  select(State, Date, Name, NameToShow, Residents.Active, EstimatedActive) %>%
  # use Residents.Active and estimated active cases (from cumulative cases) to get our best active case count
  mutate(ActiveCoalesce = ifelse(!is.na(Residents.Active), Residents.Active, EstimatedActive),
         ActiveCoalesce = ifelse(ActiveCoalesce < 0, NA, ActiveCoalesce)) %>%
  pivot_wider(names_from = Date, values_from = ActiveCoalesce) %>%
  mutate(countReal = rowSums(!is.na(select(., -State, -Name, -NameToShow, -Residents.Active, -EstimatedActive)))) %>%
  # filter(countReal > 30) %>% # only keep data we have values for more than 1 month
  select(NameToShow, `2020-03-26`:`2021-03-24`)
  
write_csv(active_cases, file.path(data_path, "active_cases.csv"))
```
